id: 10122800-f5b8-4eb7-bbbc-121c63ff24a1
title: Infinite Durability
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

