id: 0ef8f231-8d97-486e-bfa1-e40f578eed9d # Random UUID
title: Disable Internal FSR
subtitle: Disables Internal FSR downscaling
description: "Some text. \nTo add a newline."
version:
category: 2 # 1: FPS/Performance, 2: Graphics, 3: UI/UX, 4: Misc 
game:
  title id: 0100F2C011586000
  version:
    - 1.1.0
    - 1.1.1
compatibility:
  blacklist:
    - 9fd109e8-b968-497e-8de8-ab45656da9ba # Mod id which is incompatible
author:
  name: Patchanon
  link: https://gbatemp.net/download/loz-tears-of-the-kingdom-20fps-30fps-60fps-patch.37996