id: 88e57641-67d4-4f48-91b9-38afbb7607a7
title: Damage (2x)
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

