id: 0b18abd3-5ce9-4577-8ba0-18352c11a388
title: Movement Speed (1.5x)
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

