id: 5764ee59-9e8a-4ae4-9172-833992f82f19
title: Swimming Speed (3x)
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

