id: b9c83bf3-d50e-42a3-b525-6cad8446d454
title: 'Lazy Pack - 60 FPS - 720P 1X - 1440P 2X - 4K 3X - 8K 6X'
subtitle: One patch solution.
description: UI Mod Incompatible - Already has blackscreen-fix.
version:
category: 6
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
  - 62ba7b3a-052e-457e-9424-bcf57ce75171
author:
    - { name: 'ChucksFeedAndSeed, Marethyu, Wollnashorn, Patchanon, somerandompeople, ChanseyIsTheBest, OldManKain, Sweetmini' }

