id: 533c4daf-eb85-4672-9f0f-f1dfc8aeeb3b
title: 'Ultrawide 32- Ratio -1.1.1, 1.1.0 -9'
subtitle:
description:
version:
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

