id: 65a46c30-fb46-4581-b643-9548086c5964
title: 'Lazy Pack - Combo -1.1.1, 1.1.0 - UI compatible'
subtitle:
description:
version:
category: 6
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

