id: d2918d3d-5a46-4c44-8a21-e0b23d907484
title: 60fps v3 + DynamicFPS v1.31 + Cutscene-Fix - OLD
subtitle:
description:
version: 1.1.0
category: 6
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

