id: 84706472-cc97-475b-ad07-a699d2cf7410
title: 'Xbox UI Mod V9 - Normal - White'
subtitle: 
description: 'Contains Blackscreenfix, disable other instances of blackscreenfix, or this mod wont work'
version: 9
category: 7
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist: UI Blackscreen Fix
author: Alerion921

