id: b36c7084-7df8-460c-bc93-0a372e4b98f1
title: Xbox UI Mod V9 - Normal - White
subtitle: Normal layout, like default Nintendo layout, only icons replaced, with white Xbox icons.
description: "Contains Blackscreenfix, disable other instances of blackscreenfix, or this mod wont work"
version: 9.0.0
category: 3
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
  - 62ba7b3a-052e-457e-9424-bcf57ce75171
author:
    - name: Alerion921
    - link: https://gamebanana.com/mods/443354