id: 4d021dc5-ee94-43ee-b33d-1e3a7c1a7207
title: 120fps v3 + DynamicFPS v1.41
subtitle: 120fps v3 + DynamicFPS v1.41
description: "Some text. \nTo add a newline."
version: 1.1.0
category: 6 # 1: FPS/Performance, 2: Graphics, 3: UI/UX, 4: Misc, 5: Cheats, 6: Combos
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
compatibility:
  blacklist:
    - 3a2301e8-6904-4b4a-97db-47ef10bb19f2
author:
  name: Sweetmini
  link: https://github.com/HolographicWings/TOTK-Mods-collection/releases
