id: b8f98e58-3db6-4a97-afca-69fde83eba3b
title: 30fps v3 + DynamicFPS v1.31 - OLD
subtitle:
description:
version: 1.1.0
category: 6
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

