id: 183820b4-aecd-42a4-9211-ad224d4daa0e
title: Ultrawide 19.5-9
subtitle:
description:
version: 1.1.0
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

