id: 4d021dc5-ee94-43ee-b33d-1e3a7c1a7207
title: 120fps v3 + DynamicFPS v1.41
subtitle:
description:
version: 1.1.0
category: 6
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

