id: 04f51560-1e86-4f68-88a1-e4afe3d94e56
title: Pickup Sell Buy (5x)
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

