id: 2b7fc801-722a-4a98-91c8-cacda38a7630
title: Lazy Pack - 60 FPS - 1080P
subtitle:
description:
version: 1.0.0
category: 6
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

