id: 8e4e2139-c208-44d2-89e4-47a3de0cd15a
title: Moon jump - Jump in mid-air
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

