id: 6dd0c618-b845-4dce-ab9d-75ee3aaca7ad
title: Disable Internal FXAA v2
subtitle:
description:
version: 1.0.0
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.0.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

