id: 6dd0c618-b845-4dce-ab9d-75ee3aaca7ad
title: Disable Internal FXAA v2
subtitle: Disable Internal FXAA v2
description: "Some text. \nTo add a newline."
version: 1.0.0
category: 2 # 1: FPS/Performance, 2: Graphics, 3: UI/UX, 4: Misc, 5: Cheats, 6: Combos
game:
  titleId: 0100F2C011586000
  version:
    - 1.0.0
compatibility:
  blacklist:
    - 3a2301e8-6904-4b4a-97db-47ef10bb19f2
author:
  name: Sweetmini
  link: https://github.com/HolographicWings/TOTK-Mods-collection/releases
