id: a1b10877-e3bb-4c5e-8877-dfff0cd0480e
title: Perfect Thermometer - No temperature damage
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

