id: 1ad9637c-5b95-43cc-afd2-72d8512ae4b4
title: 'Lazy Pack - 30 FPS - 1080P 1X'
subtitle: One patch solution.
description: UI Mod Incompatible - Already has blackscreen-fix.
version:
category: 6
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
  - 62ba7b3a-052e-457e-9424-bcf57ce75171
author:
    - { name: 'ChucksFeedAndSeed, Marethyu, Wollnashorn, Patchanon, somerandompeople, ChanseyIsTheBest, OldManKain, Sweetmini' }

