id: 3a2301e8-6904-4b4a-97db-47ef10bb19f2 # Random UUID
title: 1008p Fxaa OFF
subtitle: Disables FXAA, FSR and DynRes
description: "Some text. \nTo add a newline."
version: 2.0
category: 2 # 1: FPS/Performance, 2: Graphics, 3: UI/UX, 4: Misc 
game:
  title id: 0100F2C011586000
  version:
    - 1.1.0
    - 1.1.1
compatibility:
  blacklist:
    - 8e6d54cc-2088-4da2-8106-07ddc3c41fae # Mod id which is incompatible
author:
  name: Sweetmini
  link: https://github.com/HolographicWings/TOTK-Mods-collection/releases