id: 800ac9a4-07cf-435f-8d0a-b601e8082d4d
title: Damage (30x)
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

