id: 06a27802-eb4e-454d-a640-7e3997d92d1d
title: Lazy Pack - 60 FPS - 720P-1440P-4K - UI compatible
subtitle:
description:
version: 1.0.0
category: 6
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

