id: d5dc6205-ed26-4b8a-8f03-6ec0131f90b8
title: 30fps Static
subtitle: 30fps Static
description: "Some text. \nTo add a newline."
version: 3.0.0
category: 1 # 1: FPS/Performance, 2: Graphics, 3: UI/UX, 4: Misc, 5: Cheats, 6: Combos
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
    - 1.0.0
author:
  name: ChucksFeedAndSeed, patchanon and somerandompeople
  link: https://gbatemp.net/download/loz-tears-of-the-kingdom-fps-static-fps-and-visual-fixes-patch-collection.37996/
