id: be3b1dbd-c807-4e3e-b535-8d5392c72b5d
title: Infinite Arrows
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

