id: a1463ca9-4c14-40ab-b54c-fbbc03cc89c6
title: 'Ultrawide 18- Ratio -1.1.1, 1.1.0 -9'
subtitle:
description:
version:
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

