id: 308d7e93-beeb-4bd1-98bb-fe6b1a026eb8
title: Attack Speed (1.5x)
subtitle: Attack Speed (1.5x)
description: "Some text. \nTo add a newline."
version: 1.1.0
category: 5 # 1: FPS/Performance, 2: Graphics, 3: UI/UX, 4: Misc, 5: Cheats, 6: Combos
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
compatibility:
  blacklist:
    - 3a2301e8-6904-4b4a-97db-47ef10bb19f2
