id: 0f153f29-88a4-439a-b859-73d9da95d135
title: Ultrawide 18-9
subtitle:
description:
version: 1.1.0
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

