id: dba6bb6c-d4bf-4bc7-b6af-5ec880a08d12
title: 'Ultrawide 19.5- Ratio -1.1.1, 1.1.0 -9 (iPhone)'
subtitle:
description:
version:
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

