id: aa2dc62d-27fc-42cd-9849-c2f872b65a1c
title: 30fps v3 + DynamicFPS v1.41 - NEW
subtitle: 30fps v3 + DynamicFPS v1.41 - NEW
description: "Some text. \nTo add a newline."
version: 1.1.0
category: 6 # 1: FPS/Performance, 2: Graphics, 3: UI/UX, 4: Misc, 5: Cheats, 6: Combos
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
compatibility:
  blacklist:
    - 3a2301e8-6904-4b4a-97db-47ef10bb19f2
author:
  name: Sweetmini
  link: https://github.com/HolographicWings/TOTK-Mods-collection/releases
