id: aa2dc62d-27fc-42cd-9849-c2f872b65a1c
title: 30fps v3 + DynamicFPS v1.41 - NEW
subtitle:
description:
version: 1.1.0
category: 6
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

