id: fbfd16dc-041f-40a0-9c00-fa1ae5c1e688
title: Movement Speed (2x)
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

