id: 11e830f4-4686-4548-bbf4-d3058c18d85d
title: Ultrawide 16-10
subtitle:
description:
version: 1.1.0
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

