id: ae1b0476-08ce-4fa8-ad1e-ef30ac1283bf
title: Movement Speed (3x)
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

