id: c03a6428-7c7e-4414-9cdb-1433ac0b06f3
title: 'Ultrawide 16- Ratio -1.1.1, 1.1.0 -10 (Steam Deck)'
subtitle:
description:
version:
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

