id: bcd96199-219d-41a1-87ca-d15a861d8471
title: Lazy Pack - 30 FPS - 720P-1440P-4K - UI compatible
subtitle:
description:
version: 1.0.0
category: 6
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

