id: 8e4e2139-c208-44d2-89e4-47a3de0cd15a
title: Moon jump - Jump in mid-air
subtitle: Moon jump - Jump in mid-air
description: "Some text. \nTo add a newline."
version: 1.1.0
category: 5 # 1: FPS/Performance, 2: Graphics, 3: UI/UX, 4: Misc, 5: Cheats, 6: Combos
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
compatibility:
  blacklist:
    - 3a2301e8-6904-4b4a-97db-47ef10bb19f2
