id: 2d0c7659-1227-4266-a36b-ca768fe78008
title: Durability (10x)
subtitle: Durability (10x)
description: "Some text. \nTo add a newline."
version: 1.0.0
category: 5 # 1: FPS/Performance, 2: Graphics, 3: UI/UX, 4: Misc, 5: Cheats, 6: Combos
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
    - 1.0.0
compatibility:
  blacklist:
    - 3a2301e8-6904-4b4a-97db-47ef10bb19f2
author:
  name: Sweetmini
  link: https://github.com/HolographicWings/TOTK-Mods-collection/releases
