id: d25c1257-2856-49e0-b299-c08c12b976bb
title: LOD Improvement
subtitle:
description:
version: 1.0.0
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
    - 1.1.1
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

