id: 84706472-cc97-475b-ad07-a699d2cf7410
title: 'Lazy Pack - 60 FPS - 1080P 1X - UI mod compatible'
subtitle: One patch solution.
description: UI Mod compatible - feel free to add a controller UI mod to this.
version:
category: 6
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
author:
    - { name: 'ChucksFeedAndSeed, Marethyu, Wollnashorn, Patchanon, somerandompeople, ChanseyIsTheBest, OldManKain, Sweetmini' }

