id: d6872271-b722-4948-8c2a-41a196ccba6e
title: Faster Bow Charge
subtitle:
description:
version: 1.1.2
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
author: NXCheats

