id: 20a6b496-e95e-40b2-ba84-e1c040a22429
title: 60fps v3.7.2 + DynamicFPS v1.41 + Cutscene-Fix - NEW
subtitle:
description:
version: 1.1.0
category: 6
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

