id: 13b8e6a3-a007-4543-b761-51c81385c88d
title: 20fps Static
subtitle:
description:
version: 3.0.0
category: 1
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

