id: 94201fd9-8f4d-4bb3-b87f-94ffc2b6e66d
title: DynamicFPS v1.42
subtitle: Do not mix with fps++
description: "Some text. \nTo add a newline."
version: 1.42
category: 1 # 1: FPS/Performance, 2: Graphics, 3: UI/UX, 4: Misc, 5: Cheats, 6: Combos
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
compatibility:
  blacklist:
    - 771f46a1-7593-4f67-832e-69839978f559
    - 006614d4-5626-4779-893f-0d06f4420a9e
author:
  name: ChucksFeedAndSeed
  link: https://gbatemp.net/download/loz-tears-of-the-kingdom-fps-static-fps-and-visual-fixes-patch-collection.37996/
