id: 211c76eb-1aba-4c8c-a565-62085cd5be6c
title: Infinite Battery
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

