id: e3b00cad-372c-42c1-938d-103dd28d9237
title: 'Ultrawide 21- Ratio -1.1.1, 1.1.0, 1.0.0 -9'
subtitle:
description:
version:
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

