id: f9c6feef-746c-44cd-b6bb-e211e129f004
title: Adhere While Climbing
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

