id: d6872271-b722-4948-8c2a-41a196ccba6e
title: Adhere While Climbing
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

