id: d2918d3d-5a46-4c44-8a21-e0b23d907484
title: 60fps v3 + DynamicFPS v1.31 + Cutscene-Fix - OLD
subtitle: 60fps v3 + DynamicFPS v1.31 + Cutscene-Fix - OLD
description: "Some text. \nTo add a newline."
version: 1.1.0
category: 6 # 1: FPS/Performance, 2: Graphics, 3: UI/UX, 4: Misc, 5: Cheats, 6: Combos
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
compatibility:
  blacklist:
    - 3a2301e8-6904-4b4a-97db-47ef10bb19f2
author:
  name: Sweetmini
  link: https://github.com/HolographicWings/TOTK-Mods-collection/releases
