id: bcc0a78d-700f-4943-96a3-a5654a487acd
title: Attack Speed (2x)
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

