id: 7bf1263f-e8b8-42c9-8724-b82ba92e48d6
title: 'Lazy Pack - 30 FPS - 720P 1X - 1440P 2X - 4K 3X - 8K 6X - UI mod compatible'
subtitle: One patch solution.
description: UI Mod compatible - feel free to add a controller UI mod to this.
version:
category: 6
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
author:
    - { name: 'ChucksFeedAndSeed, Marethyu, Wollnashorn, Patchanon, somerandompeople, ChanseyIsTheBest, OldManKain, Sweetmini' }

