id: f48f40dd-cc2a-4178-882c-f49635c2924f
title: Ultrawide 21-9
subtitle:
description:
version: 1.1.0
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

