id: be3872ba-829b-4afd-b4bf-c5f2a31b2f6d
title: Cutscene-Fix
subtitle: Cutscene-Fix
description: "Some text. \nTo add a newline."
version: 1.0.0
category: 1 # 1: FPS/Performance, 2: Graphics, 3: UI/UX, 4: Misc, 5: Cheats, 6: Combos
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1 
    - 1.1.0
    - 1.0.0
compatibility:
  blacklist:
    - 3a2301e8-6904-4b4a-97db-47ef10bb19f2
author:
  name: theboy181
