id: 49590c01-5bf9-447b-beb1-2b78ba156aed
title: Unlimited Amiibo Usage
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

