id: b1446948-e4df-42e6-a4da-7240f51d8353
title: 720p - Cheat Method - Use 2X, 3X and 6X Scaling for 1440p, 4K and 8K
subtitle: 720p - Cheat Method - Use 2X, 3X and 6X Scaling for 1440p, 4K and 8K
description: "Some text. \nTo add a newline."
version: 1.0.0
category: 2 # 1: FPS/Performance, 2: Graphics, 3: UI/UX, 4: Misc, 5: Cheats, 6: Combos
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1 
    - 1.1.0
compatibility:
  blacklist:
    - 3a2301e8-6904-4b4a-97db-47ef10bb19f2
author:
  name: Sweetmini
  link: https://github.com/HolographicWings/TOTK-Mods-collection/releases
