id: 25278b83-00d5-410b-8b58-2d798cf2f53b
title: Lazy Pack - 30 FPS - 1080P
subtitle:
description:
version: 1.0.0
category: 6
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

