id: 456587d8-24f3-4daa-a99c-70cc291ff0cc
title: New 1008p
subtitle: FXAA On - Includes FSR and DynRes Disabler  - Zero AO Bugs
description:
version: 1.0.1
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

