id: fbcdabb4-1566-44d0-8008-a09b9d1d060b
title: Reset Cheats
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

