id: 5647227f-6f63-452c-a5fc-957873ca017c
title: Climbing Speed (2x)
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

