id: 4c53d57c-383e-4af2-b31b-c68443f9edab
title: Infinite Health
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

