id: 1a65831d-b514-4508-b440-fee20ef600ca
title: Ultrawide 32-9
subtitle:
description:
version: 1.1.0
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

