id: c33c29f3-b9ad-483d-a140-5599d46cd96e
title: Infinite Stamina
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

