id: a3cfc42f-9488-4946-88a4-ba5cacf01da9
title: Disable Internal FSR sharpening shader
subtitle: Disable Internal FSR sharpening shader
description: "Some text. \nTo add a newline."
version: 1.0.0
category: 2 # 1: FPS/Performance, 2: Graphics, 3: UI/UX, 4: Misc, 5: Cheats, 6: Combos
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1 
    - 1.1.0
    - 1.0.0
compatibility:
  blacklist:
    - 3a2301e8-6904-4b4a-97db-47ef10bb19f2
author:
  name: Sweetmini
  link: https://github.com/HolographicWings/TOTK-Mods-collection/releases
